apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-security-scanner.fullname" . }}-clusterrole
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "*" ]
    verbs: [ "get" ,"watch" ,"list" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs","cronjobs" ]
    verbs: [ "get", "watch", "list", "create", "delete" ]
  - apiGroups: [ "apps" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-security-scanner.fullname" . }}-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-security-scanner.fullname" . }}-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kube-security-scanner.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-security-scanner.fullname" . }}-serviceaccount
  namespace: {{ .Release.Namespace }}
