logging:
  level:
    'io.kubernetes': TRACE

environment:
  in-cluster: true

filesystem:
  locations:
    yaml: /kube-config-scanner/yaml
    score: /kube-config-scanner/score
    trivy: /kube-config-scanner/trivy
    bench: /kube-config-scanner/bench
    kubescape: /kube-config-scanner/kubescape
