kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-security-scanner-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: kube-security-scanner-serviceaccount
    namespace: kube-security-scanner
roleRef:
  kind: ClusterRole
  name: kube-security-scanner-clusterrole
  apiGroup: rbac.authorization.k8s.io
