apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-security-scanner-deployment
  namespace: kube-security-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-security-scanner
  template:
    metadata:
      labels:
        app: kube-security-scanner
    spec:
      serviceAccountName: kube-security-scanner-serviceaccount
      containers:
        - name: kube-security-scanner
          image: kamieniarzk/kube-security-scanner:latest
          ports:
            - containerPort: 8080
          env: # create those using kubectl create secret generic mongodb-secret --from-literal=MONGO_URI=<your_mongo_uri> --from-literal=MONGO_DATABASE=<your_mongo_database> -n kube-security-scanner
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_URI
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_DATABASE
          volumeMounts:
            - name: temp-storage
              mountPath: /tmp/kube-security-scanner
            - name: logs-storage
              mountPath: /kube-security-scanner/logs
      volumes:
        - name: temp-storage
          emptyDir:
            sizeLimit: "200Mi"
        - name: logs-storage
          persistentVolumeClaim:
            claimName: kube-security-scanner-pvc
