name: Build and push container image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-jar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      - name: Upload built jar
        uses: actions/upload-artifact@v2
        with:
          name: app-jar
          path: build/libs/out.jar

  build-and-push-image:
    needs: build-jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make build/lib dir
        run: mkdir -p build/libs
      - name: Download built jar
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: build/libs
      - name: '[ DEBUG ] assert jar existence'
        run: ls -ltr build/libs/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: kamieniarzk/kube-security-scanner:latest
